name:                Lab004
version:             0.1.0.0
github:              clitetailor/Lab004
license:             BSD3
author:              Clite Tailor
maintainer:          ducnhatphung@gmail.com
copyright:           (c) 2017-2018 Clite Tailor

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/clitetailor/Lab004#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Lab004-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Lab004

tests:
  Lab004-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Lab004
