name:                Lab002
version:             0.1.0.0
github:               clitetailor/Lab002
license:             BSD3
author:              clitetailor
maintainer:          ducnhatphung@gmail.com
copyright:           (c) 2017-2018 Clite Tailor

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ clitetailor/Lab002#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  fizzbuzz:
    main:                FizzBuzz.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is FizzBuzz.main
    dependencies:
    - Lab002

  quicksort:
    main:                QuickSort.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is QuickSort.main
    dependencies:
    - Lab002

tests:
  Lab002-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Lab002
